"""Initial migration

Revision ID: 1da458f20ad2
Revises: 
Create Date: 2026-06-26 13:21:26.519949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da458f20ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_is_deleted'), 'permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_permissions_permission_code'), 'permissions', ['permission_code'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('byelaw_master',
    sa.Column('master_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('society_name', sa.String(length=255), nullable=False),
    sa.Column('society_registration_no', sa.String(length=100), nullable=False),
    sa.Column('society_type', sa.String(length=100), nullable=True),
    sa.Column('byelaw_title', sa.String(length=255), nullable=False),
    sa.Column('byelaw_version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('registrar_approval_no', sa.String(length=100), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('source_file_name', sa.String(length=255), nullable=False),
    sa.Column('source_file_type', sa.Enum('PDF', 'DOCX', 'DOC', name='file_type_enum'), nullable=False),
    sa.Column('source_file_path', sa.String(length=500), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('total_clauses', sa.Integer(), nullable=False),
    sa.Column('extraction_status', sa.Enum('Pending', 'Validated', 'Processing', 'Completed', 'Failed', 'Reviewed', name='extraction_status_enum'), nullable=False),
    sa.Column('workflow_status', sa.Enum('Draft', 'Submitted', 'Under Review', 'Verified', 'Approved', 'Rejected', 'Published', name='workflow_status_enum'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_date', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('master_id')
    )
    op.create_index(op.f('ix_byelaw_master_extraction_status'), 'byelaw_master', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_byelaw_master_is_active'), 'byelaw_master', ['is_active'], unique=False)
    op.create_index(op.f('ix_byelaw_master_is_deleted'), 'byelaw_master', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_byelaw_master_society_registration_no'), 'byelaw_master', ['society_registration_no'], unique=False)
    op.create_index(op.f('ix_byelaw_master_workflow_status'), 'byelaw_master', ['workflow_status'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('byelaw_clause',
    sa.Column('clause_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('parent_clause_id', sa.Integer(), nullable=True),
    sa.Column('clause_level', sa.Integer(), nullable=False),
    sa.Column('chapter_no', sa.String(length=50), nullable=True),
    sa.Column('clause_no', sa.String(length=50), nullable=True),
    sa.Column('clause_title', sa.String(length=255), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['byelaw_master.master_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_clause_id'], ['byelaw_clause.clause_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('clause_id')
    )
    op.create_index(op.f('ix_byelaw_clause_is_deleted'), 'byelaw_clause', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_byelaw_clause_master_id'), 'byelaw_clause', ['master_id'], unique=False)
    op.create_index(op.f('ix_byelaw_clause_parent_clause_id'), 'byelaw_clause', ['parent_clause_id'], unique=False)
    op.create_index('ft_clause_text', 'byelaw_clause', ['clause_text'], mysql_prefix='FULLTEXT')
    op.create_table('byelaw_comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['byelaw_master.master_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_byelaw_comments_is_deleted'), 'byelaw_comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_byelaw_comments_master_id'), 'byelaw_comments', ['master_id'], unique=False)
    op.create_table('upload_history',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('upload_status', sa.Enum('Success', 'Failed', name='upload_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['byelaw_master.master_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_upload_history_uploaded_by'), 'upload_history', ['uploaded_by'], unique=False)
    op.create_table('workflow_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('Draft', 'Submitted', 'Under Review', 'Verified', 'Approved', 'Rejected', 'Published', name='workflow_status_enum'), nullable=True),
    sa.Column('new_status', sa.Enum('Draft', 'Submitted', 'Under Review', 'Verified', 'Approved', 'Rejected', 'Published', name='workflow_status_enum'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['byelaw_master.master_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_workflow_history_master_id'), 'workflow_history', ['master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_history_master_id'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_upload_history_uploaded_by'), table_name='upload_history')
    op.drop_table('upload_history')
    op.drop_index(op.f('ix_byelaw_comments_master_id'), table_name='byelaw_comments')
    op.drop_index(op.f('ix_byelaw_comments_is_deleted'), table_name='byelaw_comments')
    op.drop_table('byelaw_comments')
    op.drop_index('ft_clause_text', table_name='byelaw_clause')
    op.drop_index(op.f('ix_byelaw_clause_parent_clause_id'), table_name='byelaw_clause')
    op.drop_index(op.f('ix_byelaw_clause_master_id'), table_name='byelaw_clause')
    op.drop_index(op.f('ix_byelaw_clause_is_deleted'), table_name='byelaw_clause')
    op.drop_table('byelaw_clause')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_byelaw_master_workflow_status'), table_name='byelaw_master')
    op.drop_index(op.f('ix_byelaw_master_society_registration_no'), table_name='byelaw_master')
    op.drop_index(op.f('ix_byelaw_master_is_deleted'), table_name='byelaw_master')
    op.drop_index(op.f('ix_byelaw_master_is_active'), table_name='byelaw_master')
    op.drop_index(op.f('ix_byelaw_master_extraction_status'), table_name='byelaw_master')
    op.drop_table('byelaw_master')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_permission_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_is_deleted'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
